#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WineHangouts.Resource", IsApplication=true)]

namespace WineHangouts
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int DarkBlue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_background = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cell_shape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Close = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_white = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_white1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int placeholder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int placeholder_11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int placeholder_bottiglia_lista = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int placeholder_re = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ratingstars = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int regione_lombardia = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Reimage = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int respon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sfondo_blog = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sfondo_cantine = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sfondo_catalogo_vini = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sfondo_mierecensioni = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sfondo_nuoverecensioni = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sfondo_promozioni = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sfondo_regioni = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sfondo_selezioni = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sfondo_topvini = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sfondo_wineprofile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int star = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int star_empty = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Tes = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int user = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int wine1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int wine_review = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002e
			public const int btnSubmitReview = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int button = 2131165232;
			
			// aapt resource value: 0x7f070015
			public const int button1 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int button2 = 2131165206;
			
			// aapt resource value: 0x7f07002f
			public const int fragmentContainer = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int gridview = 2131165233;
			
			// aapt resource value: 0x7f07001c
			public const int imageButton1 = 2131165212;
			
			// aapt resource value: 0x7f07000b
			public const int imageButton2 = 2131165195;
			
			// aapt resource value: 0x7f070032
			public const int imageButton3 = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int imageButton4 = 2131165235;
			
			// aapt resource value: 0x7f070027
			public const int listView1 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int listView2 = 2131165224;
			
			// aapt resource value: 0x7f070022
			public const int rating = 2131165218;
			
			// aapt resource value: 0x7f070036
			public const int ratingBar1 = 2131165238;
			
			// aapt resource value: 0x7f070002
			public const int relLayout = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int rtbProductRating = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int tableLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int tableLayout3 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int tableLayout4 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int tableRow1 = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int tableRow2 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int tableRow3 = 2131165207;
			
			// aapt resource value: 0x7f07002a
			public const int tableRow4 = 2131165226;
			
			// aapt resource value: 0x7f07001b
			public const int tableRow5 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow6 = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow7 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int tableRow78 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int tableRow8 = 2131165219;
			
			// aapt resource value: 0x7f07000a
			public const int tableRow88 = 2131165194;
			
			// aapt resource value: 0x7f070034
			public const int tableRow89 = 2131165236;
			
			// aapt resource value: 0x7f070026
			public const int tableRow9 = 2131165222;
			
			// aapt resource value: 0x7f07000f
			public const int tableRow90 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int tableRow91 = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int tableRow95 = 2131165198;
			
			// aapt resource value: 0x7f07002c
			public const int textView1 = 2131165228;
			
			// aapt resource value: 0x7f070013
			public const int textView10 = 2131165203;
			
			// aapt resource value: 0x7f070029
			public const int textView12 = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int textView13 = 2131165227;
			
			// aapt resource value: 0x7f070037
			public const int textView14 = 2131165239;
			
			// aapt resource value: 0x7f07001e
			public const int textView19 = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int textView20 = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int textView33 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int textView36 = 2131165221;
			
			// aapt resource value: 0x7f070018
			public const int textView6 = 2131165208;
			
			// aapt resource value: 0x7f07000d
			public const int textView64 = 2131165197;
			
			// aapt resource value: 0x7f070035
			public const int textView65 = 2131165237;
			
			// aapt resource value: 0x7f070012
			public const int textView66 = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int textView67 = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int textView7 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int textView8 = 2131165210;
			
			// aapt resource value: 0x7f070004
			public const int topDivider = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int txtName = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int txtPrice = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int txtRatings = 2131165190;
			
			// aapt resource value: 0x7f07002d
			public const int txtReviewComments = 2131165229;
			
			// aapt resource value: 0x7f070005
			public const int txtVintage = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommentsCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeleteReviewPop = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int detailedView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Dummy = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditReviewPopup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment1Layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Tasting = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TastingListview = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int WinePropertiesCell = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int ActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int AgrippaTheme = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int AgrippaTheme_TitleTextStyle = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int MyActionBar = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int MyTheme = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int MyTheme_ActionBarStyle = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int rtbProductRating = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int v_actionBarItemBackground = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
