#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloGridView.Resource", IsApplication=true)]

namespace HelloGridView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edit = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int heart_empty = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heart_full = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_white = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_white1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int placeholder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int placeholder_11 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int placeholder_bottiglia_lista = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int placeholder_re = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ratingstars = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int regione_lombardia = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Reimage = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int respon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sfondo_blog = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sfondo_cantine = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sfondo_catalogo_vini = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sfondo_mierecensioni = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sfondo_nuoverecensioni = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sfondo_promozioni = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sfondo_regioni = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sfondo_selezioni = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sfondo_topvini = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sfondo_wineprofile = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int star = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int star_empty = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Tes = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int trash = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int user = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int wine1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int wine_review = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002d
<<<<<<< HEAD
			public const int btnDeleteReview = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int btnSubmitReview = 2131099694;
=======
			public const int btnSubmitReview = 2131099693;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060027
			public const int button = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int button1 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int button2 = 2131099689;
			
			// aapt resource value: 0x7f060026
			public const int fragmentContainer = 2131099686;
			
			// aapt resource value: 0x7f06002a
			public const int gridview = 2131099690;
			
			// aapt resource value: 0x7f060019
			public const int imageButton1 = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int imageButton2 = 2131099659;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f060030
			public const int imageButton3 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int imageButton4 = 2131099697;
=======
			// aapt resource value: 0x7f06002e
			public const int imageButton3 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int imageButton4 = 2131099695;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060002
			public const int imgWine = 2131099650;
			
			// aapt resource value: 0x7f060024
			public const int listView1 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int listView2 = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int rating = 2131099679;
			
			// aapt resource value: 0x7f060007
			public const int rtbProductRating = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int tableLayout3 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int tableLayout4 = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int tableRow2 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int tableRow3 = 2131099670;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f06002c
			public const int tableRow4 = 2131099692;
=======
			// aapt resource value: 0x7f060033
			public const int tableRow4 = 2131099699;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060018
			public const int tableRow5 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int tableRow6 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int tableRow7 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int tableRow78 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int tableRow8 = 2131099680;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow88 = 2131099658;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f060032
			public const int tableRow89 = 2131099698;
=======
			// aapt resource value: 0x7f060030
			public const int tableRow89 = 2131099696;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060023
			public const int tableRow9 = 2131099683;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow90 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int tableRow91 = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow95 = 2131099662;
			
			// aapt resource value: 0x7f06002b
			public const int textView1 = 2131099691;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f060034
			public const int textView12 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int textView13 = 2131099701;
=======
			// aapt resource value: 0x7f060032
			public const int textView12 = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int textView13 = 2131099700;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f06001b
			public const int textView19 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int textView20 = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int textView33 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int textView36 = 2131099682;
			
			// aapt resource value: 0x7f060013
			public const int textView6 = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int textView64 = 2131099661;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f060033
			public const int textView65 = 2131099699;
=======
			// aapt resource value: 0x7f060031
			public const int textView65 = 2131099697;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060012
			public const int textView66 = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int textView67 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int textView7 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int textView8 = 2131099671;
			
			// aapt resource value: 0x7f060004
			public const int topDivider = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtName = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int txtPrice = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int txtRatings = 2131099654;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f06002f
			public const int txtReviewComments = 2131099695;
=======
			// aapt resource value: 0x7f06002c
			public const int txtReviewComments = 2131099692;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f060005
			public const int txtVintage = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommentsCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int detailedView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment1Layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
<<<<<<< HEAD
			public const int ReviewDelete = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ReviewPopup = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Tasting = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TastingListview = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WinePropertiesCell = 2130903050;
=======
			public const int ReviewPopup = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Tasting = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TastingListview = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WinePropertiesCell = 2130903049;
>>>>>>> origin/master
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int rtbProductRating = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
