#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoneword.Resource", IsApplication=true)]

namespace Phoneword
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int color_action_bar = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int CallButton = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int CallHistoryButton = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int MyButton = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int PhoneNumberText = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int TranslateButton = 2131165200;
			
			// aapt resource value: 0x7f070021
			public const int btnDesc = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int btnFoorPair = 2131165221;
			
			// aapt resource value: 0x7f070060
			public const int btnPP = 2131165280;
			
			// aapt resource value: 0x7f070027
			public const int btnProducer = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int btnReview = 2131165224;
			
			// aapt resource value: 0x7f070061
			public const int btnSec = 2131165281;
			
			// aapt resource value: 0x7f07001c
			public const int btnSubmitReview = 2131165212;
			
			// aapt resource value: 0x7f070024
			public const int btnTechNotes = 2131165220;
			
			// aapt resource value: 0x7f07005f
			public const int btnWall = 2131165279;
			
			// aapt resource value: 0x7f070023
			public const int btnWineNotes = 2131165219;
			
			// aapt resource value: 0x7f07002a
			public const int fragmentContainer = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public const int imageButton1 = 2131165231;
			
			// aapt resource value: 0x7f070057
			public const int imageButton2 = 2131165271;
			
			// aapt resource value: 0x7f07001e
			public const int imgBigWine = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int imgWine = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int lstRatingBar = 2131165203;
			
			// aapt resource value: 0x7f070029
			public const int lstWineReviews = 2131165225;
			
			// aapt resource value: 0x7f070036
			public const int rating = 2131165238;
			
			// aapt resource value: 0x7f07005d
			public const int ratingBar2 = 2131165277;
			
			// aapt resource value: 0x7f070017
			public const int rtbProductRating = 2131165207;
			
			// aapt resource value: 0x7f07005e
			public const int storePickText = 2131165278;
			
			// aapt resource value: 0x7f070002
			public const int tableLayout1 = 2131165186;
			
			// aapt resource value: 0x7f07001f
			public const int tableLayout2 = 2131165215;
			
			// aapt resource value: 0x7f070055
			public const int tableLayout3 = 2131165269;
			
			// aapt resource value: 0x7f070058
			public const int tableLayout4 = 2131165272;
			
			// aapt resource value: 0x7f070003
			public const int tableRow1 = 2131165187;
			
			// aapt resource value: 0x7f070020
			public const int tableRow2 = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int tableRow3 = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int tableRow4 = 2131165218;
			
			// aapt resource value: 0x7f07002e
			public const int tableRow5 = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int tableRow6 = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int tableRow7 = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int tableRow78 = 2131165236;
			
			// aapt resource value: 0x7f07003a
			public const int tableRow79 = 2131165242;
			
			// aapt resource value: 0x7f070037
			public const int tableRow8 = 2131165239;
			
			// aapt resource value: 0x7f07003d
			public const int tableRow80 = 2131165245;
			
			// aapt resource value: 0x7f070040
			public const int tableRow81 = 2131165248;
			
			// aapt resource value: 0x7f070043
			public const int tableRow82 = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int tableRow83 = 2131165254;
			
			// aapt resource value: 0x7f070049
			public const int tableRow84 = 2131165257;
			
			// aapt resource value: 0x7f07004c
			public const int tableRow85 = 2131165260;
			
			// aapt resource value: 0x7f07004f
			public const int tableRow86 = 2131165263;
			
			// aapt resource value: 0x7f070052
			public const int tableRow87 = 2131165266;
			
			// aapt resource value: 0x7f070056
			public const int tableRow88 = 2131165270;
			
			// aapt resource value: 0x7f07005a
			public const int tableRow89 = 2131165274;
			
			// aapt resource value: 0x7f07005c
			public const int tableRow90 = 2131165276;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070031
			public const int textView19 = 2131165233;
			
			// aapt resource value: 0x7f070033
			public const int textView20 = 2131165235;
			
			// aapt resource value: 0x7f070038
			public const int textView33 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int textView36 = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int textView46 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int textView47 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int textView48 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int textView49 = 2131165247;
			
			// aapt resource value: 0x7f070041
			public const int textView50 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int textView51 = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int textView52 = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int textView53 = 2131165253;
			
			// aapt resource value: 0x7f070047
			public const int textView54 = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int textView55 = 2131165256;
			
			// aapt resource value: 0x7f07004a
			public const int textView56 = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int textView57 = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int textView58 = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int textView59 = 2131165262;
			
			// aapt resource value: 0x7f07002b
			public const int textView6 = 2131165227;
			
			// aapt resource value: 0x7f070050
			public const int textView60 = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int textView61 = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int textView62 = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int textView63 = 2131165268;
			
			// aapt resource value: 0x7f070059
			public const int textView64 = 2131165273;
			
			// aapt resource value: 0x7f07005b
			public const int textView65 = 2131165275;
			
			// aapt resource value: 0x7f07002c
			public const int textView7 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int textView8 = 2131165229;
			
			// aapt resource value: 0x7f070035
			public const int topDivider = 2131165237;
			
			// aapt resource value: 0x7f070006
			public const int txtName = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int txtNameLabel = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int txtPrice = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int txtPriceLabel = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int txtRatingLabel = 2131165191;
			
			// aapt resource value: 0x7f070019
			public const int txtRatingTitle = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int txtRatingTitleLabel = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int txtRatings = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int txtRevier = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int txtReviewComments = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int txtReviewCommentsLabel = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int txtReviewText = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int txtStoreName = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int txtTitle = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int txtUserRatingLabel = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int txtUserRatings = 2131165194;
			
			// aapt resource value: 0x7f07001d
			public const int txtWineName = 2131165213;
			
			// aapt resource value: 0x7f070001
			public const int wineList = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EnoListing = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listView_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ReviewList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ReviewPopup = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Tab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WineDetailAndReview = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WineStores = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int callHistory = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int foodRatingBar = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
