#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloTabsICS.Resource", IsApplication=true)]

namespace HelloTabsICS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_white = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_white1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sfondo_blog = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sfondo_cantine = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sfondo_catalogo_vini = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sfondo_mierecensioni = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sfondo_nuoverecensioni = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sfondo_promozioni = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sfondo_regioni = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sfondo_selezioni = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sfondo_topvini = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sfondo_wineprofile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sumanth = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int fragmentContainer = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sampleTextView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int example = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment1Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment1Layout2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment1Layout3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Tab = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
